/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.form;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class FormPhanHoi extends javax.swing.JFrame {

    DefaultTableModel model;
    /**
     * Creates new form FormPhanHoi
     */
    Connection cnt = null;
    PreparedStatement ptn = null;
    ResultSet rs = null;
    int q, i, id, delete;
    String DanhGia = null;

    public FormPhanHoi() {
        setLocationRelativeTo(null);
        setResizable(false);
        initComponents();
        model = (DefaultTableModel) tblPhanHoi.getModel();
        
    }

    public void ngu() {
        
    }

    public void table() {
        
        model.addRow(new Object[]{"", DanhGia, txtPhanHoi.getText()});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbx1s = new javax.swing.JCheckBox();
        cbx2s = new javax.swing.JCheckBox();
        cbx3s = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhanHoi = new javax.swing.JTable();
        txtPhanHoi = new javax.swing.JTextField();
        btnGui = new javax.swing.JButton();
        cbx5s = new javax.swing.JCheckBox();
        cbx4s = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbx1s.setText("1 Sao");
        cbx1s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx1sActionPerformed(evt);
            }
        });

        cbx2s.setText("2 sao");
        cbx2s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx2sActionPerformed(evt);
            }
        });

        cbx3s.setText("3 sao");
        cbx3s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx3sActionPerformed(evt);
            }
        });

        tblPhanHoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ Tên", "Đánh Giá", "Nhận Xét"
            }
        ));
        tblPhanHoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhanHoiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPhanHoi);

        btnGui.setText("Gửi");
        btnGui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiActionPerformed(evt);
            }
        });

        cbx5s.setText("5 sao");
        cbx5s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx5sActionPerformed(evt);
            }
        });

        cbx4s.setText("4 sao");
        cbx4s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx4sActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPhanHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cbx1s)
                            .addGap(18, 18, 18)
                            .addComponent(cbx2s)
                            .addGap(18, 18, 18)
                            .addComponent(cbx3s)
                            .addGap(18, 18, 18)
                            .addComponent(cbx4s)
                            .addGap(18, 18, 18)
                            .addComponent(cbx5s))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGui)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbx1s)
                    .addComponent(cbx2s)
                    .addComponent(cbx3s)
                    .addComponent(cbx4s)
                    .addComponent(cbx5s))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPhanHoi, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGui)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiActionPerformed
        // TODO add your handling code here:
        table();
    }//GEN-LAST:event_btnGuiActionPerformed

    private void tblPhanHoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhanHoiMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tblPhanHoiMouseClicked

    private void cbx5sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx5sActionPerformed
        // TODO add your handling code here:
        DanhGia = cbx5s.getText();
        model.setRowCount(0);
        
    }//GEN-LAST:event_cbx5sActionPerformed

    private void cbx4sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx4sActionPerformed
        // TODO add your handling code here:
        DanhGia = cbx4s.getText();

    }//GEN-LAST:event_cbx4sActionPerformed

    private void cbx3sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx3sActionPerformed
        // TODO add your handling code here:
        DanhGia = cbx3s.getText();
        
    }//GEN-LAST:event_cbx3sActionPerformed

    private void cbx2sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx2sActionPerformed
        // TODO add your handling code here:
        DanhGia = cbx2s.getText();
        
    }//GEN-LAST:event_cbx2sActionPerformed

    private void cbx1sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx1sActionPerformed
        // TODO add your handling code here:
        DanhGia = cbx1s.getText();
        
    }//GEN-LAST:event_cbx1sActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPhanHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPhanHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPhanHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPhanHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPhanHoi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGui;
    private javax.swing.JCheckBox cbx1s;
    private javax.swing.JCheckBox cbx2s;
    private javax.swing.JCheckBox cbx3s;
    private javax.swing.JCheckBox cbx4s;
    private javax.swing.JCheckBox cbx5s;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPhanHoi;
    private javax.swing.JTextField txtPhanHoi;
    // End of variables declaration//GEN-END:variables
}
